name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb-JOSIAH
  LOCATION: westus2
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 5539351e-d7fe-4067-b8d2-094cd10926f8
  WEBAPP-NAME: eshoponweb-webapp-JOSIAH

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload bicep artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: .net-app

      - name: Download bicep artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure WebApp Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      - name: Publish Website to WebApp via Azure CLI
        run: |
          az webapp deploy \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --name ${{ env.WEBAPP-NAME }} \
            --src-path .net-app/app.zip \
            --type zip
